const canvas=document.querySelector("#starfield");const context=canvas?.getContext("2d");const meteorLayer=document.querySelector("#meteor-layer");const reduced=window.matchMedia("(prefers-reduced-motion: reduce)").matches;let stars=[],width=0,height=0,ratio=1;
const random=(min,max)=>Math.random()*(max-min)+min;
function resize(){if(!canvas)return;width=innerWidth;height=innerHeight;ratio=Math.min(devicePixelRatio||1,2);canvas.width=width*ratio;canvas.height=height*ratio;canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;context.setTransform(ratio,0,0,ratio,0,0);stars=Array.from({length:Math.min(Math.floor(width*height/3600),360)},()=>({x:Math.random()*width,y:Math.random()*height,r:random(.45,1.85),a:random(.22,.95),s:random(.012,.045),t:random(0,Math.PI*2),d:random(.03,.18),h:Math.random()>.72?"199,246,255":"255,255,255"}))}
function render(time=0){context.clearRect(0,0,width,height);const glow=context.createRadialGradient(width*.5,height*.38,0,width*.5,height*.38,Math.max(width,height)*.7);glow.addColorStop(0,"rgba(28,52,92,.14)");glow.addColorStop(1,"rgba(0,0,0,0)");context.fillStyle=glow;context.fillRect(0,0,width,height);stars.forEach(star=>{star.t+=star.s;star.y+=star.d;if(star.y>height+4){star.y=-4;star.x=Math.random()*width}context.beginPath();context.fillStyle=`rgba(${star.h},${Math.max(.08,Math.min(1,star.a+Math.sin(star.t+time*.00045)*.22))})`;context.arc(star.x,star.y,star.r,0,Math.PI*2);context.fill()});requestAnimationFrame(render)}
function meteor(){if(reduced||!meteorLayer)return;const el=document.createElement("span"),left=Math.random()>.5,sx=left?random(-220,width*.2):random(width*.68,width+120),sy=random(-20,height*.58),tx=left?random(width*.7,width*1.25):-random(width*.7,width*1.25),ty=random(height*.26,height*.72),duration=random(900,1550);el.className="meteor";el.style.left=`${sx}px`;el.style.top=`${sy}px`;el.style.setProperty("--travel-x",`${tx}px`);el.style.setProperty("--travel-y",`${ty}px`);el.style.setProperty("--duration",`${duration}ms`);el.style.setProperty("--angle",`${Math.atan2(ty,tx)*180/Math.PI}deg`);meteorLayer.appendChild(el);setTimeout(()=>el.remove(),duration+120);setTimeout(meteor,random(950,3200))}
function reveal(){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.16,rootMargin:"0px 0px -70px"});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el))}
function pointerGlow(){document.querySelectorAll(".project-card").forEach(card=>{card.addEventListener("pointermove",event=>{const rect=card.getBoundingClientRect();card.style.background=`radial-gradient(circle at ${event.clientX-rect.left}px ${event.clientY-rect.top}px,rgba(140,236,255,.16),transparent 34%),linear-gradient(145deg,rgba(255,255,255,.115),rgba(255,255,255,.035)),rgba(255,255,255,.045)`});card.addEventListener("pointerleave",()=>card.style.background="")})}
function gate(){const gate=document.querySelector("#landing-gate"),button=document.querySelector("#enter-universe");if(!gate||!button)return;if(sessionStorage.getItem("universe-entered")){gate.remove();return}button.addEventListener("click",()=>{document.body.classList.add("gate-open");sessionStorage.setItem("universe-entered","true");setTimeout(()=>gate.classList.add("is-dismissed"),1300);setTimeout(()=>gate.remove(),2200)})}
function activeNav(){const page=document.body.dataset.page;document.querySelector(`[data-nav="${page}"]`)?.classList.add("active")}
addEventListener("resize",resize);resize();if(canvas){render();if(!reduced)setTimeout(meteor,700)}reveal();pointerGlow();gate();activeNav();
